typography_spectrum: 0.6125578684732318
color:
  brandColors:
    - '#0cbbd0'
    - '#08829a'
    - '#065d71'
    - '#043249'
    - '#4bbeda'
  brandStrength: 0.3951268708333373
  lightness: 0.29648922639898956
  saturation: 0.6119474922306836
  rhythmicContrast: 0.33229933655820787
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25592
analytics:
  google: null
  facebook: null
  twitter: null
name: Nauset Acquisitions Inc
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'What goes on inside the walls is more important than the walls. '
description: Let us help you afford a school your whole community can be proud of.
purpose: []
